# Generated by Django 2.2 on 2019-04-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnelsystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='employee_number',
            field=models.IntegerField(unique=True),
        ),
    ]
